/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegistryRouteImport } from './routes/registry'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RegistryNameRouteImport } from './routes/registry.$name'
import { Route as CategoryCategoryIdRouteImport } from './routes/category.$categoryId'
import { Route as AdminIndexRegistriesRouteImport } from './routes/admin.index-registries'
import { Route as RepoOwnerNameRouteImport } from './routes/repo.$owner.$name'

const RegistryRoute = RegistryRouteImport.update({
  id: '/registry',
  path: '/registry',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RegistryNameRoute = RegistryNameRouteImport.update({
  id: '/$name',
  path: '/$name',
  getParentRoute: () => RegistryRoute,
} as any)
const CategoryCategoryIdRoute = CategoryCategoryIdRouteImport.update({
  id: '/category/$categoryId',
  path: '/category/$categoryId',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRegistriesRoute = AdminIndexRegistriesRouteImport.update({
  id: '/admin/index-registries',
  path: '/admin/index-registries',
  getParentRoute: () => rootRouteImport,
} as any)
const RepoOwnerNameRoute = RepoOwnerNameRouteImport.update({
  id: '/repo/$owner/$name',
  path: '/repo/$owner/$name',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/registry': typeof RegistryRouteWithChildren
  '/admin/index-registries': typeof AdminIndexRegistriesRoute
  '/category/$categoryId': typeof CategoryCategoryIdRoute
  '/registry/$name': typeof RegistryNameRoute
  '/repo/$owner/$name': typeof RepoOwnerNameRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/registry': typeof RegistryRouteWithChildren
  '/admin/index-registries': typeof AdminIndexRegistriesRoute
  '/category/$categoryId': typeof CategoryCategoryIdRoute
  '/registry/$name': typeof RegistryNameRoute
  '/repo/$owner/$name': typeof RepoOwnerNameRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/registry': typeof RegistryRouteWithChildren
  '/admin/index-registries': typeof AdminIndexRegistriesRoute
  '/category/$categoryId': typeof CategoryCategoryIdRoute
  '/registry/$name': typeof RegistryNameRoute
  '/repo/$owner/$name': typeof RepoOwnerNameRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/registry'
    | '/admin/index-registries'
    | '/category/$categoryId'
    | '/registry/$name'
    | '/repo/$owner/$name'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/registry'
    | '/admin/index-registries'
    | '/category/$categoryId'
    | '/registry/$name'
    | '/repo/$owner/$name'
  id:
    | '__root__'
    | '/'
    | '/registry'
    | '/admin/index-registries'
    | '/category/$categoryId'
    | '/registry/$name'
    | '/repo/$owner/$name'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  RegistryRoute: typeof RegistryRouteWithChildren
  AdminIndexRegistriesRoute: typeof AdminIndexRegistriesRoute
  CategoryCategoryIdRoute: typeof CategoryCategoryIdRoute
  RepoOwnerNameRoute: typeof RepoOwnerNameRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/registry': {
      id: '/registry'
      path: '/registry'
      fullPath: '/registry'
      preLoaderRoute: typeof RegistryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/registry/$name': {
      id: '/registry/$name'
      path: '/$name'
      fullPath: '/registry/$name'
      preLoaderRoute: typeof RegistryNameRouteImport
      parentRoute: typeof RegistryRoute
    }
    '/category/$categoryId': {
      id: '/category/$categoryId'
      path: '/category/$categoryId'
      fullPath: '/category/$categoryId'
      preLoaderRoute: typeof CategoryCategoryIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/index-registries': {
      id: '/admin/index-registries'
      path: '/admin/index-registries'
      fullPath: '/admin/index-registries'
      preLoaderRoute: typeof AdminIndexRegistriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/repo/$owner/$name': {
      id: '/repo/$owner/$name'
      path: '/repo/$owner/$name'
      fullPath: '/repo/$owner/$name'
      preLoaderRoute: typeof RepoOwnerNameRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface RegistryRouteChildren {
  RegistryNameRoute: typeof RegistryNameRoute
}

const RegistryRouteChildren: RegistryRouteChildren = {
  RegistryNameRoute: RegistryNameRoute,
}

const RegistryRouteWithChildren = RegistryRoute._addFileChildren(
  RegistryRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  RegistryRoute: RegistryRouteWithChildren,
  AdminIndexRegistriesRoute: AdminIndexRegistriesRoute,
  CategoryCategoryIdRoute: CategoryCategoryIdRoute,
  RepoOwnerNameRoute: RepoOwnerNameRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
