/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as BrowseRouteImport } from './routes/browse'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RegistryNameRouteImport } from './routes/registry.$name'
import { Route as AdminIndexRegistriesRouteImport } from './routes/admin.index-registries'
import { Route as RepoOwnerNameRouteImport } from './routes/repo.$owner.$name'

const BrowseRoute = BrowseRouteImport.update({
  id: '/browse',
  path: '/browse',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RegistryNameRoute = RegistryNameRouteImport.update({
  id: '/registry/$name',
  path: '/registry/$name',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRegistriesRoute = AdminIndexRegistriesRouteImport.update({
  id: '/admin/index-registries',
  path: '/admin/index-registries',
  getParentRoute: () => rootRouteImport,
} as any)
const RepoOwnerNameRoute = RepoOwnerNameRouteImport.update({
  id: '/repo/$owner/$name',
  path: '/repo/$owner/$name',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/browse': typeof BrowseRoute
  '/admin/index-registries': typeof AdminIndexRegistriesRoute
  '/registry/$name': typeof RegistryNameRoute
  '/repo/$owner/$name': typeof RepoOwnerNameRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/browse': typeof BrowseRoute
  '/admin/index-registries': typeof AdminIndexRegistriesRoute
  '/registry/$name': typeof RegistryNameRoute
  '/repo/$owner/$name': typeof RepoOwnerNameRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/browse': typeof BrowseRoute
  '/admin/index-registries': typeof AdminIndexRegistriesRoute
  '/registry/$name': typeof RegistryNameRoute
  '/repo/$owner/$name': typeof RepoOwnerNameRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/browse'
    | '/admin/index-registries'
    | '/registry/$name'
    | '/repo/$owner/$name'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/browse'
    | '/admin/index-registries'
    | '/registry/$name'
    | '/repo/$owner/$name'
  id:
    | '__root__'
    | '/'
    | '/browse'
    | '/admin/index-registries'
    | '/registry/$name'
    | '/repo/$owner/$name'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BrowseRoute: typeof BrowseRoute
  AdminIndexRegistriesRoute: typeof AdminIndexRegistriesRoute
  RegistryNameRoute: typeof RegistryNameRoute
  RepoOwnerNameRoute: typeof RepoOwnerNameRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/browse': {
      id: '/browse'
      path: '/browse'
      fullPath: '/browse'
      preLoaderRoute: typeof BrowseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/registry/$name': {
      id: '/registry/$name'
      path: '/registry/$name'
      fullPath: '/registry/$name'
      preLoaderRoute: typeof RegistryNameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/index-registries': {
      id: '/admin/index-registries'
      path: '/admin/index-registries'
      fullPath: '/admin/index-registries'
      preLoaderRoute: typeof AdminIndexRegistriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/repo/$owner/$name': {
      id: '/repo/$owner/$name'
      path: '/repo/$owner/$name'
      fullPath: '/repo/$owner/$name'
      preLoaderRoute: typeof RepoOwnerNameRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BrowseRoute: BrowseRoute,
  AdminIndexRegistriesRoute: AdminIndexRegistriesRoute,
  RegistryNameRoute: RegistryNameRoute,
  RepoOwnerNameRoute: RepoOwnerNameRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
