/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegistryRouteImport } from './routes/registry'
import { Route as RegistriesRouteImport } from './routes/registries'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRegistriesRouteImport } from './routes/admin.index-registries'

const RegistryRoute = RegistryRouteImport.update({
  id: '/registry',
  path: '/registry',
  getParentRoute: () => rootRouteImport,
} as any)
const RegistriesRoute = RegistriesRouteImport.update({
  id: '/registries',
  path: '/registries',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRegistriesRoute = AdminIndexRegistriesRouteImport.update({
  id: '/admin/index-registries',
  path: '/admin/index-registries',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/registries': typeof RegistriesRoute
  '/registry': typeof RegistryRoute
  '/admin/index-registries': typeof AdminIndexRegistriesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/registries': typeof RegistriesRoute
  '/registry': typeof RegistryRoute
  '/admin/index-registries': typeof AdminIndexRegistriesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/registries': typeof RegistriesRoute
  '/registry': typeof RegistryRoute
  '/admin/index-registries': typeof AdminIndexRegistriesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/registries' | '/registry' | '/admin/index-registries'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/registries' | '/registry' | '/admin/index-registries'
  id: '__root__' | '/' | '/registries' | '/registry' | '/admin/index-registries'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  RegistriesRoute: typeof RegistriesRoute
  RegistryRoute: typeof RegistryRoute
  AdminIndexRegistriesRoute: typeof AdminIndexRegistriesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/registry': {
      id: '/registry'
      path: '/registry'
      fullPath: '/registry'
      preLoaderRoute: typeof RegistryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/registries': {
      id: '/registries'
      path: '/registries'
      fullPath: '/registries'
      preLoaderRoute: typeof RegistriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/index-registries': {
      id: '/admin/index-registries'
      path: '/admin/index-registries'
      fullPath: '/admin/index-registries'
      preLoaderRoute: typeof AdminIndexRegistriesRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  RegistriesRoute: RegistriesRoute,
  RegistryRoute: RegistryRoute,
  AdminIndexRegistriesRoute: AdminIndexRegistriesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
